cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^', include('shop.urls', namespace='shop')),
]

shop/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Category(models.Model):

  name = models.CharField(max_length=250, db_index=True)
  slug = models.SlugField(max_length=250, db_index=True, unique=True)

  class Meta:
    verbose_name = "Category"
    verbose_name_plural = "Categories"

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
  
  category = models.ForeignKey(Category, related_name='products')
  name = models.CharField(max_length=250, db_index=True)
  slug = models.SlugField(max_length=250, db_index=True)
  image = models.ImageField(upload_to='products', blank=True)
  description = models.TextField(blank=True)
  price = models.DecimalField(max_digits=10, decimal_places=2)
  stock = models.IntegerField()
  avilable = models.BooleanField(default=True)
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)

  class Meta:
    index_together = (('id', 'slug'),)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('shop:product_detail', args=[self.id, self.slug])

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 31)]


class CartAddProductForm(forms.Form):
  quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
  update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
  cart = Cart(request)
  product = get_object_or_404(Product, id=product_id)
  form = CartAddProductForm(request.POST)
  if form.is_valid():
    cd = form.cleaned_data
    cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
  return redirect('cart:cart_detail')


def cart_remove(request, product_id):
  cart = Cart(request)
  product = get_object_or_404(Product, id=product_id)
  cart.remove(product)
  return redirect('cart:cart_detail')


def cart_detail(request):
  cart = Cart(request)
  return render(request, 'cart/detail.html', {'cart': cart})

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm


def product_list(request, category_slug=None):
  category = None
  categories = Category.objects.all()
  products = Product.objects.filter(avilable=True)
  if category_slug:
    category = get_object_or_404(Category, slug=category_slug)
    products = products.filter(category=category)
  return render(request, 'shop/product/list.html', {'category': category, 'categories': categories, 'products': products})


def product_detail(request, id, slug):
  product = get_object_or_404(Product, id=id, slug=slug, avilable=True)
  cart_product_form = CartAddProductForm()
  return render(request, 'shop/product/detail.html', {'product': product, 'cart_product_form': cart_product_form})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block content %}
  
  <p>Your shoping cart</p>
  <table>
    <tr>
      <th>name:</th>
      <th>remove:</th>
    </tr>
    {% for item in cart %}
      {% with product=item.product %}
      <tr>
        <th>{{ product.name }}</th>
        <th><a href="{% url 'cart:cart_remove' product.id %}">remove</a></th>
      </tr>
      {% endwith %}
    {% endfor %}
  </table>

{% endblock content %}

shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html>

  <head>
    <meta charset="utf-8"/>
  </head>
  
  <body>
    <div class="cart">
      {% with total_items=cart|length %}
      <a href="{% url 'cart:cart_detail' %}">Your cart </a>{{ total_items }} items.
      {% endwith %}
    </div>
    <div class="content">
      {% block content %}
        
      {% endblock content %}
    </div>
  </body>

</html>

shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block content %}
  <div class"detail">  
    {% if product.image %}<img src="{{ product.image.url }}" alt="">{% endif %}
    <p>{{ product.name }}</p>
    <p>{{ product.price }}</p>

    <form action="{% url "cart:cart_add" product.id %}" method="post">
    {{ cart_product_form }}
    {% csrf_token %}
    <input type="submit" value="Add to cart">

    <p>{{ product.description }}</p>
    <p>{{ product.category }}</p>
  </div>
{% endblock content %}

shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block content %}
  
  <div id="sidebar">
    <p>Categories:</p>    
    <ul>
      {% for cat in categories %}
        <li><a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a></li>
      {% endfor %}
    </ul>
  </div>
  
  <div id="main">
    <p>{% if category %}{{ category.name }}{% else %}Products:{% endif %}</p>
    {% for product in products %}
      <div class"product">
        <a href="{{ product.get_absolute_url }}">
          {% if product.image %}<img src="{{ product.image.url }}" alt="">{% endif %}
          <p>{{ product.name }}</p>
          <p>{{ product.price }}</p>
        </a>
      </div>
    {% endfor %}
  </div>

{% endblock content %}